CREATE TABLE [queues].[JediQueue]
(
	Id INT IDENTITY(1,1) PRIMARY KEY NONCLUSTERED,
	[Data] VARCHAR(1000),
	LastModifiedDate DATETIME2(7)
)
WITH(
	MEMORY_OPTIMIZED = ON,
	DURABILITY=SCHEMA_ONLY
);
GO


